{
 "title": "SMTS",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Sensor #2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Dust",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "conmgm3" } },
   "targets": [
    {
     "dataset": "SMTS",
     "rawSql": "SELECT Timestamp, Sample FROM SMTS.DUST WHERE Node = 2"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 9, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "SMTS",
     "rawSql": "SELECT Timestamp, Sample FROM SMTS.TEMPERATURE WHERE Node = 2 "
    }
   ]
  },
  {
   "title": "Regolith",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 5, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    {
     "dataset": "SMTS",
     "rawSql": "SELECT Timestamp, Sample FROM SMTS.REGOLITH WHERE Node = 2"
    }
   ]
  },
  { "title": "Sensor #3", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Dust",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 5, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "conmgm3" } },
   "targets": [
    {
     "dataset": "SMTS",
     "rawSql": "SELECT Timestamp, Sample FROM SMTS.DUST WHERE Node = 3"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 9, "x": 5, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "SMTS",
     "rawSql": "SELECT Sample FROM SMTS.TEMPERATURE WHERE Node = 3"
    }
   ]
  },
  {
   "title": "Regolith",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 5, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "masskg" } },
   "targets": [
    {
     "dataset": "SMTS",
     "rawSql": "SELECT Timestamp, Sample FROM SMTS.REGOLITH WHERE Node = 3"
    }
   ]
  }
 ]
}